import React from "react";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const DashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default DashboardLayout;
